#python3
'''
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''
def findTheDifference(s, t):
	for letter in t:
		if t.count(letter) != s.count(letter):
			return letter

if __name__ == '__main__':
	print(findTheDifference('abcd', 'abcde'))
	print(findTheDifference('a', 'aa'))